name: Deploy to Firebase

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # 2. Check if Jekyll config exists
      - name: Check for Jekyll config
        id: check_jekyll
        run: |
          if [ -f "_config.yml" ]; then
            echo "jekyll=true" >> $GITHUB_OUTPUT
          else
            echo "jekyll=false" >> $GITHUB_OUTPUT
          fi
      
      # 3. Build Jekyll site (if it exists)
      - name: Build Jekyll site
        if: steps.check_jekyll.outputs.jekyll == 'true'
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/srv/jekyll \
            jekyll/jekyll:latest \
            jekyll build --destination ./public
      
      # 4. Move static files to public folder (if no Jekyll)
      - name: Prepare static files
        if: steps.check_jekyll.outputs.jekyll == 'false'
        run: |
          mkdir -p public
          # Copy all files except hidden and config files
          find . -maxdepth 1 -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" \) \
            -exec cp {} public/ \;
          echo "Using static files only"
      
      # 5. Setup Node.js for Firebase CLI
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      # 6. Install Firebase CLI
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      
      # 7. Deploy to Firebase
      - name: Deploy to Firebase
        run: |
          firebase deploy \
            --project whaai-c388e \
            --token "${{ secrets.FIREBASE_TOKEN }}" \
            --only hosting
