name: Deploy to Firebase Hosting

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build Jekyll site
      run: |
        docker run --rm -v ${{ github.workspace }}:/srv/jekyll jekyll/jekyll:latest \
          jekyll build --destination ./_site
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Deploy to Firebase
      run: firebase deploy --project whaai-c388e --token ${{ secrets.FIREBASE_TOKEN }}
