name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repository code
      - uses: actions/checkout@v3

      # 2. Set up Node.js environment (required for Firebase CLI)
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install Firebase CLI globally
      - run: npm install -g firebase-tools

      # 4. Deploy to Firebase using your secret token
      - run: firebase deploy --project w haai-c388e --token ${{ secrets.FIREBASE_TOKEN }}
