name: Deploy to Firebase Hosting

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    # Build Jekyll locally and commit _site directory
    - name: Build Jekyll site
      run: |
        docker run --rm -v ${{ github.workspace }}:/srv/jekyll jekyll/jekyll:latest \
          jekyll build --destination ./_site
    
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' # Alternative to token
        projectId: whaai-c388e
        channelId: live
